name: Code Coverage

on:
  push:
    paths:
      - "BiFuncLib/*.py"
      - "pytest/*.py"
      - ".github/workflows/code_coverage.yml"
  pull_request:
    paths:
      - "BiFuncLib/*.py"
      - "pytest/*.py"
      - ".github/workflows/code_coverage.yml"
  workflow_dispatch:

jobs:
  codecovPy:
    name: Codecov workflow
    runs-on: windows-latest
    env:
      PYTHON: "3.12"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install BiFuncLib & dependencies
        run: |
          pip install -e .

      - name: BiFuncLib coverage report
        run: |
          pip install pytest pytest-cov
          cd ./pytest
          pytest --cov=BiFuncLib -v --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./pytest/coverage.xml
          fail_ci_if_error: true
